#!/usr/bin/env node
// Stop: incrementally count canonical "용어(설명)" exposures in the final assistant
// message and update the per-session fade counters. Defensive by contract:
// missing last_assistant_message or stop_hook_active=true leaves counters untouched,
// and a repeated Stop for the same message (same hash) is a no-op.
// Learning hook: fail open (exit 0, no output) on any internal error.
import crypto from 'node:crypto';
import { readStdinJson, failOpen } from './lib/hookio.js';
import { loadSession, saveSession } from './lib/state.js';
import { loadTerms } from './lib/capsule.js';

function stripCode(text) {
  return text
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`\n]*`/g, ' ');
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Canonical exposure: the real term immediately followed by "(" + a parenthetical
// that begins with the first characters of the canonical explanation. This shape is
// generated by the novice glossary rule, so bare mentions and user quotes don't count.
function countsInMessage(message, terms) {
  const text = stripCode(message);
  const counted = [];
  for (const t of terms) {
    const prefix = t.explanation.slice(0, 6);
    const gloss = (t.aliases || []).find((a) => /[가-힣]/.test(a));
    const pattern = new RegExp(
      `${escapeRegExp(t.term)}\\s?\\((?:${escapeRegExp(gloss ?? '')}[:：]?\\s*)?${escapeRegExp(prefix)}`,
      'i',
    );
    if (pattern.test(text)) counted.push(t.term);
  }
  return counted;
}

function main() {
  const input = readStdinJson();
  if (input.stop_hook_active === true) return;
  const message = input.last_assistant_message;
  if (typeof message !== 'string' || message === '') return;
  const sessionId = input.session_id;
  if (typeof sessionId !== 'string' || sessionId === '') return;

  const hash = crypto.createHash('sha256').update(message).digest('hex');
  const session = loadSession(sessionId);
  if (session.last_message_hash === hash) return;
  session.last_message_hash = hash;

  const counted = countsInMessage(message, loadTerms().terms);
  for (const term of counted) {
    session.term_counts[term] = (session.term_counts[term] ?? 0) + 1;
    // A reset term that gets explained again starts a fresh fade cycle.
    if (Array.isArray(session.reset_terms) && session.reset_terms.includes(term)) {
      session.reset_terms = session.reset_terms.filter((x) => x !== term);
    }
  }
  saveSession(sessionId, session);
}

try {
  main();
  process.exit(0);
} catch {
  failOpen();
}
